[package]
name = "demo"
version = "0.1.0"
authors = ["maik"]

[dependencies]

tephra = {path = "../tephra"}
tephra-vulkan = {path = "../backend/vulkan"}
tephra-derive = {path = "../tephra-derive"}
ash = {git = "https://github.com/MaikKlein/ash.git", branch="generator"}

